src/lib/common/commonConstruct.ts
src/lib/manager/aws/lambdaManager.ts
src/lib/manager/aws/vpcManager.ts

fix(vpc): Adding vpcName and cidr props to createVpc

fix(lambda): Adding vpcSubnets to lambdaFunction.

---

src/lib/manager/aws/codebuild-manager.ts

fix(cloudfront): Update cloudfront invalidation log group name with id prefix

---

src/lib/construct/site-with-ecs-backend/main.ts
src/lib/construct/static-site/main.ts
src/lib/manager/aws/cloudfront-manager.ts
src/lib/types/aws/index.ts
src/test/common/cdkConfig/waf.json
src/test/construct/static-site-with-ecs-backend.test.ts
src/test/construct/static-site.test.ts

Reverts gradientedge/cdk-utils#166

Revert "feat(sites): #165 Add WAF to `static-site` and `site-with-ecs-backend` constructs"

---

src/lib/construct/site-with-ecs-backend/main.ts
src/lib/manager/aws/ecs-manager.ts
src/lib/types/aws/index.ts

Using `ecs-manager` for `SiteWithEcsBackend` contruct

feat(ecs): using `ecs-manager` for `SiteWithEcsBackend` contruct

---

package.json
src/lib/manager/aws/lambda-manager.ts
src/lib/manager/aws/sqs-manager.ts
src/lib/types/aws/index.ts
src/test/common/cdkConfig/lambdas.json
src/test/construct/static-site-with-ecs-backend.test.ts

Adding default values for DLQ & RedriveQ

feat(sqs): adding default values for DLQ & RedriveQ

---

app/api-destined-function/package.json
package.json
yarn.lock

Renaming `init` script as it's a reserved keyword with latest versions

feat(deps): Bumping lerna dependency

---

src/lib/manager/aws/sqs-manager.ts

Adding support for FIFO DLQ and ReDrive Queue

feat(dlq): adding support for FIFO DLQ and ReDrive Queue

---

src/lib/manager/aws/event-manager.ts
src/lib/manager/aws/iam-manager.ts
src/lib/types/aws/index.ts
src/test/common/cdkConfig/pipes.json
src/test/manager/event-manager.test.ts

Adding support for EB Pipe from SQS => SFN

feat(pipes): adding support for EB Pipe from SQS => SFN

---

src/lib/manager/aws/iam-manager.ts
src/lib/manager/aws/lambda-manager.ts
src/test/manager/iam-manager.test.ts

- feat(iam): Adding statements for appconfig, xray and kms
- feat(lambda): Enabling global log retention config for docker lambdas

feat: IAM & Lambda enhancements

---

.github/workflows/ci.yml

Updates github token to fix publishing documentation. For error refer to [workflow run](https://github.com/gradientedge/cdk-utils/actions/runs/8984922927/job/24677942063)

fix: publishing documentation

---

src/lib/aws/services/eventbridge/main.ts
src/lib/aws/services/eventbridge/types.ts
src/test/aws/common/cdkConfig/pipes.json
src/test/aws/construct/piped-event-handler.test.ts

add input template to pipe lambda target

feat: add input template to pipe lambda target

---

src/lib/azure/common/construct.ts
src/lib/azure/common/resource-name-formatter.ts
src/lib/azure/common/types.ts
src/lib/azure/services/api-management/main.ts
src/lib/azure/services/app-configuration/main.ts
src/lib/azure/services/app-service/main.ts
src/lib/azure/services/application-insights/main.ts
src/lib/azure/services/cosmosdb/main.ts
src/lib/azure/services/dns/main.ts
src/lib/azure/services/eventgrid/main.ts
src/lib/azure/services/function/main.ts
src/lib/azure/services/key-vault/main.ts
src/lib/azure/services/log-analytics-workspace/main.ts
src/lib/azure/services/servicebus/main.ts
src/lib/azure/services/storage/main.ts

add resource formatter for azure

feat(azure): add resource formatter for azure

---

src/lib/azure/common/index.ts

expose azure resource formatter

fix(azure): expose azure resource formatter

---

package.json
pnpm-lock.yaml

Upgrades azure provider to the latest version. Forgot to push the commit to in previous PR.
1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?
[pr-url]: https://github.com/gradientedge/cdk-utils/pulls

fix(azure): upgrade azure provider to the latest version

---

src/lib/azure/services/key-vault/main.ts

fix(azure): enable purge protection

---

src/lib/azure/services/function/main.ts

add a retry for random 503 error

fix(azure): add a retry for random 503 error

---

src/lib/azure/common/tagging.ts

fix(azure): add a tag ignore for aspect

---

src/lib/azure/services/storage/main.ts
src/lib/azure/services/storage/types.ts
src/test/azure/common/common-azure-construct.test.ts

generate sas for blob container

fix(azure): generate sas for blob container

---

src/lib/azure/services/eventgrid/main.ts

add retry config to event grid subscription

feat: add retry config to event grid subscription

---

src/lib/azure/services/servicebus/main.ts
src/test/azure/services/servicebus.test.ts

add duplicate detection to service bus queue

feat: add duplicate detection to service bus queue

---

src/lib/azure/services/storage/main.ts

feat: add sas start date param

---

src/lib/azure/services/servicebus/main.ts
src/test/azure/services/servicebus.test.ts

feat: add ttl to service bus queue

---

src/lib/azure/services/servicebus/main.ts
src/test/azure/services/servicebus.test.ts

change ttl format of service bus queue

feat: change ttl format of service bus queue

---

src/lib/azure/services/api-management/main.ts
src/lib/azure/services/api-management/types.ts
src/test/azure/common/cdkConfig/api-management.json
src/test/azure/services/api-management-manager.test.ts

feat: azure add rate limit to apim

---

src/lib/azure/services/api-management/main.ts
src/test/azure/services/api-management-manager.test.ts

feat: azure add unique counter key
